---
title: "ITS Checklist"
author: "Work Planners // SE Region"
date: '2022-07-07'
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
library(tinytex)

knitr::opts_chunk$set(echo = TRUE)
```


# Integrity Tree Service Checklist

##how to make a bullet list

* Item 1
  * sub item 1 
  * sub item 2 
    * sub-sub-item 1b





These lists are for protocol recollection for the various repetitive tasks to ensure proper steps are followed each time of asking.

## Pre Trip Truck

- [ ] 360 Walkaround
   * watch for debris
   * tire pressure
   * oilcheck for leaks
   * watch for kids
   * check lugnuts (wheels)
- [ ] Check for Fluids (Under the hood)
   * oil
   * brake fluid (make sure it's above the add line)
   * steering fluid
   * transmission fluid (if applicable) 
- [ ] Check Fire Extinguisher and Safety Kit (Monthly / As Needed)

## Pre Trip Trailer

- [ ] Checking Trailer Connection
   * chains are crossed
   * breakaway cable has an unobstructed line to the truck
   * pigtail (i.e. electrical connection) has a firm connection to the female end
- [ ] Tires are unobstructed (nothing hiding underneath the trailer)
- [ ] Load securement 
   * straps
- [ ] Marker Lights
   * brake signal
   * turn signal
   * hazard
   
## Post Trip Trailer (Unloading + Dropping Off)

- [ ] Take out tire stoppers
   * ?

## End of Work Week File/Work Management Tasks
- [ ] UKG/Timesheet
   * Friday 9AM or End of Day
- [ ] Hotel Requests
   * Thursday, by lunch
- [ ] PJBs
   * Validate and Ensure Accuracy
   * Last Work Day
- [ ] Control Reports 
   * End of Last Work Day
- [ ] Safety Tailgate
   * Friday 5PM
- [ ] SAP/Concur
   * Validate expenses and upload receipts
   * End of Month






















